In [28]:
import numpy as np

x_1 = np.array([2000,2,1])

print(f"x_1 feature vector: {x_1}")
print(f"x_1 type: {type(x_1)}")

x_1 feature vector: [2000    2    1]
x_1 type: <class 'numpy.ndarray'>


In [29]:
x_2 = np.array([2560,3,1])

sum_x_1_x_2 = x_1 + x_2
print(f"Sum of x_1 and x_2: {sum_x_1_x_2}")

multification = x_1 * x_2
print(f"Product of x_1 and x_2: {multification}")



Sum of x_1 and x_2: [4560    5    2]
Product of x_1 and x_2: [5120000       6       1]


In [30]:
x = np.array([[2000,2,1]
              ,[2560,3,1]
              ,[3000,4,1],
              [3000,4,1],
              [3000,4,1]])

print(f"Feature matrix x:\n{x}")
print (f"Feature matrix x shape: {x.shape}")

Feature matrix x:
[[2000    2    1]
 [2560    3    1]
 [3000    4    1]
 [3000    4    1]
 [3000    4    1]]
Feature matrix x shape: (5, 3)


In [31]:
print(x[0,1]) # Accessing the second element of the first row
print(x[1,0]) # Accessing the first element of the second row

2
2560


In [32]:
print(x[1:4,:]) # Accessing the first two elements of the third row

[[2560    3    1]
 [3000    4    1]
 [3000    4    1]]


In [33]:
print(x[:3,:2])

[[2000    2]
 [2560    3]
 [3000    4]]


In [ ]:
three_d_array = np.array([[[1,2,3],[4,5,6]],
                         [[7,8,9],[10,11,12]],
                         [[13,14,15],[16,17,18]]])

print(f"3D array:\n{three_d_array}")
print(f"3D array shape: {three_d_array.shape}")

3D array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
3D array shape: (3, 2, 3)
