In [1]:
import numpy as np
mat_A = np.array([[4, 5, 3 ], [1, 2, 3], [6, 7, 5]])
mat_B = np.array([[1, 4, 9  ], [3, 5, 8], [6, 3, 1]])

mat_C = mat_A @ mat_B
print("Matrix A:\n", mat_A)
print("Matrix B:\n", mat_B)
print("Result of A @ B:\n", mat_C)

Matrix A:
 [[4 5 3]
 [1 2 3]
 [6 7 5]]
Matrix B:
 [[1 4 9]
 [3 5 8]
 [6 3 1]]
Result of A @ B:
 [[ 37  50  79]
 [ 25  23  28]
 [ 57  74 115]]
